services:
  bitcoin-postgres:
    image: postgres:latest
    volumes:
      - /home/hunter/bd_bitcoin:/var/lib/postgresql/data
    container_name: bitcoin_posgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - "5440:5432"
    restart: always
  